spring.application.name=ph-transit-graph

spring.datasource.url=jdbc:postgresql://localhost:5432/ph_transit_graph
spring.datasource.username=transituser
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080
